- hosts: all

  tasks:
      - name: Ensure code directory
        file: dest={{ clone_dir }} state=directory

      - name: Deploy app
        git: repo=git@github.com:sumitsamson/myansiblelearning.git dest={{ clone_dir }}